### PR TITLE
fix: error in getQuery() of httpFunctions.js

### PR DESCRIPTION
**Pull request by Flam3rboy**
for some weird reason for every request it is throwing this error:
```
TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
```

#### Checklist

- [ ] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by adrai** [comment]
Can you please provide a reproducible example?

**Comment by Flam3rboy** [comment]
Sadly I can't isolate the error and is probably caused by a dependency.
Atm we are using patch-package to fix this error, but it is not a very clean solution.
That's why we wanted to do a PR and fix this issue.

If you really want to reproduce it, you can setup [fosscord-api](http://github.com/fosscord/fosscord-api)
It'll use your local mongo database by default and can just open ``http://localhost:3001/``
Make sure not to execute ``postinstall`` in ``package.json`` by just deleting the line.
```
git clone http://github.com/fosscord/fosscord-api
npm i
npm start
```

**Comment by adrai** [comment]
Can you try with v3.1.3?

**Comment by Flam3rboy** [comment]
yes it worked 👍

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏

**Pull request closed without merging**
