### PR TITLE
Add a way to configure sameSite for cookie lookup

### PR DESCRIPTION
**Pull request by martpie**
#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included
- [x] documentation is changed or added

Tests are not yet done, but I am not sure if I can add some. I have to check them.

### CODE REVIEW

**Comment by adrai** [comment]
if doing it this way: I probably need to do a major version: https://github.com/i18next/i18next-http-middleware/pull/8/files#diff-683eb46a4ffc28f203e819a091800a59R81

if doing it that way: I only need to do a minor version: https://github.com/i18next/i18next-http-middleware/issues/7#issuecomment-632749240

what do you think?

**Comment by adrai** [comment]
So we co for major then... @martpie @isaachinman ? v2.0.0

**Comment by martpie** [comment]
I don't think so, because `options.cookieSameSite` will be undefined, therefore the cookie option won't be appended to the `Set-Cookie` header 

https://github.com/i18next/i18next-http-middleware/blob/1942189ab213f6d2332aad6e0663dd47e809b196/lib/languageLookups/cookie.js#L34

**Comment by martpie** [comment]
Unless I am missing something with my damaged brain 🤔

**Comment by adrai** [comment]
Ahh, this distracted me: https://github.com/i18next/i18next-http-middleware/pull/8/files#diff-04c6e90faac2675aa89e2176d2eec7d8R302
I was thinking this was this: https://github.com/i18next/i18next-http-middleware/blob/master/lib/LanguageDetector.js#L11 (the defaults)

**Comment by adrai** [comment]
Ok, should we merge it at is, and to a minor version or change also the defaults and do a major version?

**Comment by martpie** [comment]
I think a minor version is much more reasonable, I'll do the changes quickly

**Comment by adrai** [comment]
I'm just thinking... Would it be better (for the future) to add `cookieSameSite: 'strict'` to the defaults?

**Comment by martpie** [comment]
I think it makes sense, but it would be a breaking change for sure

**Comment by adrai** [comment]
for me, there is no problem to do a major version ;-)
But @isaachinman needs to update the dependency in next-i18next... and probably also do a major?

**Comment by adrai** [comment]
let's do 2 releases:
1 minor, as is
1 major with the default...

what do you think?

**Comment by martpie** [comment]
You're the boss here, I'm fine with both solutions :p just having a way to solve my warning is enough for me right now (so re-resolving my dependencies should bring me the latest minor version of `i18next-http-middleware`)

**Comment by adrai** [comment]
the community is the boss ;-)

let's do 2 releases

**Comment by isaachinman** [comment]
Thanks @adrai. @martpie Want to open a PR on `next-i18next` to propagate these changes?

**Comment by martpie** [comment]
Yep, I'll do that!

**Comment by adrai** [comment]
v1.3.1
v2.0.0

**Pull request merged**
