### PR TITLE
add param lookupHeaderRegex

### PR DESCRIPTION
**Pull request by svengau**
#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] documentation is changed or added

FR https://github.com/i18next/i18next-http-middleware/issues/16

### CODE REVIEW

**Comment by adrai** [comment]
Will look at it deeper in a couple of hours...
Can’t the new regex not be the default for all?

**Comment by adrai** [comment]
What do you think?
Should we change the default to: /((([a-z]{2})|([a-z]{4}))-?([A-Z]{2})?)\s*;?\s*(q=([0-9.]+))?/gi ?

**Comment by svengau** [comment]
It will be a breaking change, because it may change the behaviour in some
cases.

**Comment by adrai** [comment]
It will just be more permissive... in the validation... I think it's ok, to change the default...

**Comment by adrai** [comment]
Nevertheless v3 was released a couple of days ago... I don't think there are so many that already have updated to v3.
Can you change it, I will merge it.

**Comment by adrai** [comment]
included in v3.0.1

**Pull request merged**
