### PR TITLE
Add Types

### PR DESCRIPTION
**Pull request by fominua**
#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] documentation is changed or added

### CODE REVIEW

**Comment by adrai** [comment]
Thank you for this contribution.
Can you add also some tests?
Btw: Would you like to maintain the types in case of issues?

**Comment by fominua** [comment]
For what functions needed tests?

I think I'm ready to support some issue regarding types.

**Comment by adrai** [comment]
something to check the types, maybe like: https://github.com/adrai/i18next-next/blob/main/test/types/i18next.test-d.ts

**Comment by fominua** [comment]
Hey! I added tests for types definition.

**Comment by adrai** [comment]
Thank you.
Are you familiar with deno?
Just saw, you imported express types... this will probably not work when using deno.
If you have some time can you add this:
image
and run npm run test:deno ?
Maybe it would be better (if possible) to have express agnostic types. Can this be done?

**Comment by fominua** [comment]
I dont familiar deno, but i check this problem.

**Comment by fominua** [comment]
@adrai you update version on npm?

**Comment by adrai** [comment]
currently afk...
but was waiting for your feedback regarding express agnostic types...

**Comment by fominua** [comment]
We can remove Express.js from dependencies, but for Express.js applications the types will be less informative than they could be.

**Comment by adrai** [comment]
i18next-http-middleware itself is express agnostic

**Comment by adrai** [comment]
@fominua any update on this or would you like me to release a new version?

**Comment by adrai** [comment]
@isaachinman would this be ok for next-i18next?

**Comment by isaachinman** [comment]
@adrai Looks fine to me, but I could have sworn `i18next-http-middleware` already had types? Regardless, the `next-i18next` package will be moving away from relying on the i18next ecosystem for lang detection or routing.

**Comment by adrai** [comment]
> @fominua any update on this or would you like me to release a new version?

@fominua ?

**Comment by fominua** [comment]
> > @fominua any update on this or would you like me to release a new version?
> 
> @fominua ?

Hey! Sorry, I got a little sick last week. I plan to return to this question in a few days, because it is still relevant to me.

**Comment by fominua** [comment]
> @adrai Looks fine to me, but I could have sworn `i18next-http-middleware` already had types? Regardless, the `next-i18next` package will be moving away from relying on the i18next ecosystem for lang detection or routing.

I didn't find any types in this package. Can you tell us more about this?

**Comment by isaachinman** [comment]
@fominua Hope you are feeling better now!

I was mistaken – what I was remembering was [having to extend Express types](https://github.com/isaachinman/next-i18next/blob/76280e422a0508241772e6940bf92f7a940755f2/types.d.ts#L77), because this package _didn't_ export types. Sorry for the confusion!

**Comment by fominua** [comment]
> @fominua Hope you are feeling better now!
> 
> I was mistaken – what I was remembering was [having to extend Express types](https://github.com/isaachinman/next-i18next/blob/76280e422a0508241772e6940bf92f7a940755f2/types.d.ts#L77), because this package _didn't_ export types. Sorry for the confusion!

@isaachinman Yes, that's the problem. What do you think is the best solution now?

I am thinking of removing the Express types from this package and replacing them with arbitrary objects so that this package does not depend on Express.

**Comment by isaachinman** [comment]
@fominua Not sure exactly what you mean. I would assume that, having removed the Express dependency, this package should simply extend the built-in NodeJs HTTP types.

**Comment by adrai** [comment]
> @fominua Not sure exactly what you mean. I would assume that, having removed the Express dependency, this package should simply extend the built-in NodeJs HTTP types.

Because of Deno support this is probably not ok.

**Comment by isaachinman** [comment]
Unfortunately I do not have any experience supporting types for Deno that rely on NodeJs built-ins, so I can't really offer any advice. I would assume that if this code compiles and runs in Deno, they should be able to make sense of the types, but that's probably a naive assumption.

**Comment by fominua** [comment]
I can suggest the following option https://github.com/i18next/i18next-http-middleware/pull/32

We can remove expressjs dependencies, but only use Core instead.

If you try to abandon this package, it will lead to duplication of some types, because the creation of these types from Node types will be this duplication.

**Comment by adrai** [comment]
Does it work when adding this line? https://github.com/i18next/i18next-http-middleware/pull/30#issuecomment-750828069

**Comment by fominua** [comment]
> Does it work when adding this line? [#30 (comment)](https://github.com/i18next/i18next-http-middleware/pull/30#issuecomment-750828069)

npm run lint
npm run test
npm run test:deno
npm run build

The commands completed successfully, if that's what you mean.

**Comment by adrai** [comment]
perfect

**Comment by adrai** [comment]
out of curiosity, does it also work when changing this to typescript? https://github.com/i18next/i18next-http-middleware/blob/master/test/deno/middleware.abc.js

**Comment by fominua** [comment]
I see it as being possible to test results, but not types. I may not fully understand how tests work in Deno, but I do not see an option for type checking here.

**Comment by adrai** [comment]
Will try to check this after having merged... will let you know if there is any type issue

**Comment by fominua** [comment]
> Will try to check this after having merged... will let you know if there is any type issue

ok, thank you

**Comment by adrai** [comment]
I removed the types for Deno again... it did not work: https://github.com/i18next/i18next-http-middleware/runs/1687685457?check_suite_focus=true
https://github.com/i18next/i18next-http-middleware/commit/a2d7ffe44a23e0beeb48a61b4e5376b831b5e96d

let's keep it like this, until there's someone who wants to have Types for Deno...

**Comment by adrai** [comment]
Should we release a new version now?
What do you suggest major? minor?

**Comment by fominua** [comment]
> ready to release...
> Should we release a new version now?
> What do you suggest @fominua major? minor?

It would be nice. I think it's still minor

**Comment by fominua** [comment]
> I removed the types for Deno again... it did not work: https://github.com/i18next/i18next-http-middleware/runs/1687685457?check_suite_focus=true
> [a2d7ffe](https://github.com/i18next/i18next-http-middleware/commit/a2d7ffe44a23e0beeb48a61b4e5376b831b5e96d)
> 
> let's keep it like this, until there's someone who wants to have Types for Deno...

I will return to this question in a few days. Perhaps it will work out. Then we can release a new version.

**Comment by adrai** [comment]
v3.1.0 has just been released...
Thank you again for all your help.

**Comment by fominua** [comment]
Thank you!

In the coming days I will work with this package, if I notice other problems, I will inform you)

**Pull request merged**
